### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by jredd** [cedvdb/ng2draggable#21]
I'm using angular cli 1.6.7 with angular 5.2

ERROR in ./node_modules/ng2draggable/draggable.directive.ts
Module build failed: Error: ./node_modules/ng2draggable/draggable.directive.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (./node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:662:23)
    at plugin.done.then (/.jdev/sites/angular/infinity-frontend/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/shared/discussion/discussion.module.ts 15:28-71
 @ ./src/app/model-monitoring/view/view.module.ts
 @ ./src/app/model-monitoring/model-monitoring.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by jredd** [comment]
fixed it by adding the this to the tsconfig.app.json file

```
"include": [
    "**/*",
    "../node_modules/ng2draggable/draggable.directive.ts"
  ],
```

**Comment by shakoorattari** [comment]
Its still not working in angular. added in angular.json
