### ISSUE TITLE
Not compiling in Angular 6

### ISSUE THREAD

**Issue by Polyterative** [cedvdb/ng2draggable#25]
Adding the error message here

```
ERROR in ./node_modules/ng2draggable/draggable.directive.ts
Module build failed: Error: [...]/node_modules\ng2draggable\draggable.directive.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository 
to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile ([...]\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:708:23)
    at plugin.done.then ([...]\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:178:7)
i ｢wdm｣: Failed to compile.
```

**Comment by Stuart88** [comment]
+1 for this. I'm getting the same problem. Also using Angular 6.
